USE ContosoRetailDW

--QUESTÃO 1
DECLARE @VALOR1 INT
SET @VALOR1 = 10

DECLARE @VALOR2 INT
SET @VALOR2 = 5

DECLARE @VALOR3 INT
SET @VALOR3 = 34

DECLARE @VALOR4 INT
SET @VALOR4 = 7

--A-)

DECLARE @VALOR1 INT
SET @VALOR1 = 10
DECLARE @VALOR2 INT
SET @VALOR2 = 5
DECLARE @SOMA INT
SET @SOMA = @VALOR1 + @VALOR2

SELECT @SOMA AS 'SOMA'

--B-)
DECLARE @VALOR3 INT
SET @VALOR3 = 34
DECLARE @VALOR4 INT
SET @VALOR4 = 7
DECLARE @SUBTRAÇÃO INT
SET @SUBTRAÇÃO = @VALOR3 - @VALOR4
SELECT @SUBTRAÇÃO AS 'SUBTRAÇÃO'

--C-)
DECLARE @VALOR1 INT
SET @VALOR1 = 10
DECLARE @VALOR4 INT
SET @VALOR4 = 7
DECLARE @MULTIPLICAÇÃO INT
SET @MULTIPLICAÇÃO = @VALOR1 * @VALOR4 
SELECT @MULTIPLICAÇÃO AS 'MULTIPLICAÇÃO'

--D-)
DECLARE @VALOR3 INT
SET @VALOR3 = 34
DECLARE @VALOR4 INT
SET @VALOR4 = 7
DECLARE @DIVISÃO FLOAT 
SET @DIVISÃO = CAST(@VALOR3 AS FLOAT) / CAST(@VALOR4 AS FLOAT)
SELECT ROUND(@DIVISÃO,2) AS 'DIVISÃO'

--QUESTÃO 2

DECLARE @PRODUTO VARCHAR(20)
SET @PRODUTO = 'Celular'

DECLARE @QUANTIDADE INT
SET @QUANTIDADE = 12

DECLARE @PREÇO FLOAT
SET @PREÇO = 9.99

DECLARE @FATURAMENTO FLOAT
SET @FATURAMENTO = @QUANTIDADE * @PREÇO

SELECT 
	@PRODUTO AS 'Produto',
	@QUANTIDADE AS 'Quantidade',
	@PREÇO AS 'Preço',
	@FATURAMENTO AS 'Faturamento'

--QUESTÃO 3
DECLARE @NOME_DONO CHAR(5)
SET @NOME_DONO = 'André'

DECLARE @NASCIMENTO_DONO DATE
SET @NASCIMENTO_DONO = '10-02-1998'

DECLARE @NUM_PETS INT
SET @NUM_PETS = 2

SELECT
 FRASE= 'Meu nome é '+ @NOME_DONO +', nasci em'+ FORMAT(CAST(@NASCIMENTO_DONO AS datetime),'dd/MM/yyyy') +' e tenho '+CAST(@NUM_PETS AS varchar(MAX)) +' pets.'

 --QUESTÂO 4
 DECLARE @LOJAS VARCHAR (MAX)
 SET @LOJAS = ''
 SELECT @LOJAS = @LOJAS + StoreName +', '+CHAR(10)
 FROM DimStore
 WHERE CloseDate IS NOT  NULL  AND CloseDate BETWEEN '01/01/2008' AND '31/12/2008'
 PRINT 'As lojas fechadas no ano de 2008 foram: '+ LEFT(@LOJAS,DATALENGTH(@LOJAS)-3)

 --QUESTÂO 5
 DECLARE @PRODUTOS VARCHAR (MAX)
 SET @PRODUTOS = ''
 SELECT @PRODUTOS = @PRODUTOS + ProductName +', '+CHAR(10)
 FROM DimProduct INNER JOIN DimProductSubcategory ON DimProductSubcategory.ProductSubcategoryKey= DimProduct.ProductSubcategoryKey
 WHERE ProductSubcategoryName = 'Lamps'
 PRINT LEFT(@PRODUTOS,DATALENGTH(@PRODUTOS)-3)
